symbol_list = {
    "Aarti Industries Limited": "AARTIIND.NS",
    "ABB Limited": "ABB.NS",
    "Abbott India Limited": "ABBOTINDIA.NS",
    "Aditya Birla Capital Limited": "ABCAPITAL.NS",
    "Aditya Birla Fashion and Retail Limited": "ABFRL.NS",
    "ACC Limited": "ACC.NS",
    "Adani Enterprises Limited": "ADANIENT.NS",
    "Adani Ports and Special Economic Zone Limited": "ADANIPORTS.NS",
    "Alkem Laboratories Limited": "ALKEM.NS",
    "Ambuja Cements Limited": "AMBUJACEM.NS",
    "Apollo Hospitals Enterprise Limited": "APOLLOHOSP.NS",
    "Apollo Tyres Limited": "APOLLOTYRE.NS",
    "Ashok Leyland Limited": "ASHOKLEY.NS",
    "Asian Paints Limited": "ASIANPAINT.NS",
    "Astral Limited": "ASTRAL.NS",
    "Atul Limited": "ATUL.NS",
    "AU Small Finance Bank Limited": "AUBANK.NS",
    "Aurobindo Pharma Limited": "AUROPHARMA.NS",
    "Axis Bank Limited": "AXISBANK.NS",
    "Bajaj Auto Limited": "BAJAJ-AUTO.NS",
    "Bajaj Finserv Limited": "BAJAJFINSV.NS",
    "Bajaj Finance Limited": "BAJFINANCE.NS",
    "Balkrishna Industries Limited": "BALKRISIND.NS",
    "Balrampur Chini Mills Limited": "BALRAMCHIN.NS",
    "Bandhan Bank Limited": "BANDHANBNK.NS",
    "Bank of Baroda": "BANKBARODA.NS",
    "Bata India Limited": "BATAINDIA.NS",
    "Bharat Electronics Limited": "BEL.NS",
    "Berger Paints India Limited": "BERGEPAINT.NS",
    "Bharat Forge Limited": "BHARATFORG.NS",
    "Bharti Airtel Limited": "BHARTIARTL.NS",
    "Bharat Heavy Electricals Limited": "BHEL.NS",
    "Biocon Limited": "BIOCON.NS",
    "Bosch Limited": "BOSCHLTD.NS",
    "Bharat Petroleum Corporation Limited": "BPCL.NS",
    "Britannia Industries Limited": "BRITANNIA.NS",
    "Birlasoft Limited": "BSOFT.NS",
    "Canara Bank": "CANBK.NS",
    "Can Fin Homes Limited": "CANFINHOME.NS",
    "Chambal Fertilizers & Chemicals Limited": "CHAMBLFERT.NS",
    "Cholamandalam Investment and Finance Company Limited": "CHOLAFIN.NS",
    "Cipla Limited": "CIPLA.NS",
    "Coal India Limited": "COALINDIA.NS",
    "Coforge Limited": "COFORGE.NS",
    "Colgate-Palmolive (India) Limited": "COLPAL.NS",
    "Container Corporation of India Limited": "CONCOR.NS",
    "Coromandel International Limited": "COROMANDEL.NS",
    "Crompton Greaves Consumer Electricals Limited": "CROMPTON.NS",
    "City Union Bank Limited": "CUB.NS",
    "Cummins India Limited": "CUMMINSIND.NS",
    "Dabur India Limited": "DABUR.NS",
    "Dalmia Bharat Limited": "DALBHARAT.NS",
    "Deepak Nitrite Limited": "DEEPAKNTR.NS",
    "Delta Corp Limited": "DELTACORP.NS",
    "Divis Laboratories Limited": "DIVISLAB.NS",
    "Dixon Technologies (India) Limited": "DIXON.NS",
    "DLF Limited": "DLF.NS",
    "Dr. Reddy's Laboratories Limited": "DRREDDY.NS",
    "Eicher Motors Limited": "EICHERMOT.NS",
    "Escorts Limited": "ESCORTS.NS",
    "Exide Industries Limited": "EXIDEIND.NS",
    "Federal Bank Limited": "FEDERALBNK.NS",
    "GAIL (India) Limited": "GAIL.NS",
    "Glenmark Pharmaceuticals Limited": "GLENMARK.NS",
    "GMR Infrastructure Limited": "GMRINFRA.NS",
    "Gujarat Fluorochemicals Limited": "GNFC.NS",
    "Godrej Consumer Products Limited": "GODREJCP.NS",
    "Godrej Properties Limited": "GODREJPROP.NS",
    "Granules India Limited": "GRANULES.NS",
    "Grasim Industries Limited": "GRASIM.NS",
    "Gujarat Gas Limited": "GUJGASLTD.NS",
    "Hindustan Aeronautics Limited": "HAL.NS",
    "Havells India Limited": "HAVELLS.NS",
    "HCL Technologies Limited": "HCLTECH.NS",
    "HDFC Asset Management Company Limited": "HDFCAMC.NS",
    "HDFC Bank Limited": "HDFCBANK.NS",
    "HDFC Life Insurance Company Limited": "HDFCLIFE.NS",
    "Hero MotoCorp Limited": "HEROMOTOCO.NS",
    "Hindalco Industries Limited": "HINDALCO.NS",
    "Hindustan Copper Limited": "HINDCOPPER.NS",
    "Hindustan Petroleum Corporation Limited": "HINDPETRO.NS",
    "Hindustan Unilever Limited": "HINDUNILVR.NS",
    "Indiabulls Housing Finance Limited": "IBULHSGFIN.NS",
    "ICICI Bank Limited": "ICICIBANK.NS",
    "ICICI Lombard General Insurance Company Limited": "ICICIGI.NS",
    "ICICI Prudential Life Insurance Company Limited": "ICICIPRULI.NS",
    "Vodafone Idea Limited": "IDEA.NS",
    "IDFC Limited": "IDFC.NS",
    "IDFC First Bank Limited": "IDFCFIRSTB.NS",
    "Indian Energy Exchange Limited": "IEX.NS",
    "Indraprastha Gas Limited": "IGL.NS",
    "Indian Hotels Company Limited": "INDHOTEL.NS",
    "India Cements Limited": "INDIACEM.NS",
    "IndiaMART InterMESH Limited": "INDIAMART.NS",
    "InterGlobe Aviation Limited": "INDIGO.NS",
    "IndusInd Bank Limited": "INDUSINDBK.NS",
    "Indus Towers Limited": "INDUSTOWER.NS",
    "Infosys Limited": "INFY.NS",
    "Indian Oil Corporation Limited": "IOC.NS",
    "IPCA Laboratories Limited": "IPCALAB.NS",
    "Indian Railway Catering and Tourism Corporation Limited": "IRCTC.NS",
    "ITC Limited": "ITC.NS",
    "Jindal Steel & Power Limited": "JINDALSTEL.NS",
    "JK Cement Limited": "JKCEMENT.NS",
    "JSW Steel Limited": "JSWSTEEL.NS",
    "Jubilant Foodworks Limited": "JUBLFOOD.NS",
    "Kotak Mahindra Bank Limited": "KOTAKBANK.NS",
    "L&T Finance Holdings Limited": "L&TFH.NS",
    "Dr. Lal PathLabs Limited": "LALPATHLAB.NS",
    "Laurus Labs Limited": "LAURUSLABS.NS",
    "LIC Housing Finance Limited": "LICHSGFIN.NS",
    "Larsen & Toubro Limited": "LT.NS",
    "Larsen & Toubro Infotech Limited": "LTIM.NS",
    "L&T Technology Services Limited": "LTTS.NS",
    "Lupin Limited": "LUPIN.NS",
    "Mahindra & Mahindra Limited": "M&M.NS",
    "Mahindra & Mahindra Financial Services Limited": "M&MFIN.NS",
    "Manappuram Finance Limited": "MANAPPURAM.NS",
    "Marico Limited": "MARICO.NS",
    "Maruti Suzuki India Limited": "MARUTI.NS",
    "United Spirits Limited": "MCDOWELL-N.NS",
    "Multi Commodity Exchange of India Limited": "MCX.NS",
    "Metropolis Healthcare Limited": "METROPOLIS.NS",
    "Max Financial Services Limited": "MFSL.NS",
    "Mahanagar Gas Limited": "MGL.NS",
    "Motherson Sumi Systems Limited": "MOTHERSON.NS",
    "Mphasis Limited": "MPHASIS.NS",
    "MRF Limited": "MRF.NS",
    "Muthoot Finance Limited": "MUTHOOTFIN.NS",
    "National Aluminium Company Limited": "NATIONALUM.NS",
    "Info Edge (India) Limited": "NAUKRI.NS",
    "Navin Fluorine International Limited": "NAVINFLUOR.NS",
    "Nestle India Limited": "NESTLEIND.NS",
    "NMDC Limited": "NMDC.NS",
    "NTPC Limited": "NTPC.NS",
    "Oberoi Realty Limited": "OBEROIRLTY.NS",
    "Oracle Financial Services Software Limited": "OFSS.NS",
    "Oil and Natural Gas Corporation Limited": "ONGC.NS",
    "Page Industries Limited": "PAGEIND.NS",
    "Piramal Enterprises Limited": "PEL.NS",
    "Persistent Systems Limited": "PERSISTENT.NS",
    "Petronet LNG Limited": "PETRONET.NS",
    "Power Finance Corporation Limited": "PFC.NS",
    "Pidilite Industries Limited": "PIDILITIND.NS",
    "PI Industries Limited": "PIIND.NS",
    "Punjab National Bank": "PNB.NS",
    "Polycab India Limited": "POLYCAB.NS",
    "Power Grid Corporation of India Limited": "POWERGRID.NS",
    "PVR Limited": "PVRINOX.NS",
    "Ramco Cements Limited": "RAMCOCEM.NS",
    "RBL Bank Limited": "RBLBANK.NS",
    "REC Limited": "RECLTD.NS",
    "Reliance Industries Limited": "RELIANCE.NS",
    "Steel Authority of India Limited": "SAIL.NS",
    "SBI Cards and Payment Services Limited": "SBICARD.NS",
    "SBI Life Insurance Company Limited": "SBILIFE.NS",
    "State Bank of India": "SBIN.NS",
    "Shree Cement Limited": "SHREECEM.NS",
    "Shriram City Union Finance Limited": "SHRIRAMFIN.NS",
    "Siemens Limited": "SIEMENS.NS",
    "SRF Limited": "SRF.NS",
    "Sun Pharmaceutical Industries Limited": "SUNPHARMA.NS",
    "Sun TV Network Limited": "SUNTV.NS",
    "Syngene International Limited": "SYNGENE.NS",
    "Tata Chemicals Limited": "TATACHEM.NS",
    "Tata Communications Limited": "TATACOMM.NS",
    "Tata Consumer Products Limited": "TATACONSUM.NS",
    "Tata Motors Limited": "TATAMOTORS.NS",
    "Tata Power Company Limited": "TATAPOWER.NS",
    "Tata Steel Limited": "TATASTEEL.NS",
    "Tata Consultancy Services Limited": "TCS.NS",
    "Tech Mahindra Limited": "TECHM.NS",
    "Titan Company Limited": "TITAN.NS",
    "Torrent Pharmaceuticals Limited": "TORNTPHARM.NS",
    "Trent Limited": "TRENT.NS",
    "TVS Motor Company Limited": "TVSMOTOR.NS",
    "United Breweries Limited": "UBL.NS",
    "UltraTech Cement Limited": "ULTRACEMCO.NS",
    "UPL Limited": "UPL.NS",
    "Vedanta Limited": "VEDL.NS",
    "Voltas Limited": "VOLTAS.NS",
    "Wipro Limited": "WIPRO.NS",
    "Zee Entertainment Enterprises Limited": "ZEEL.NS",
    "Zydus Wellness Limited": "ZYDUSLIFE.NS",
}
